#!C:\Users\liu95\Desktop\Yu\ITTA02\assignment-02-digital-signal-processing-Leosssss\env\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
